config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "events#index"
  resources :events do
    resources :event_attendees, only: [:create]
  end
  resources :users


  #  get 'users/show'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :event_attendees
  has_many :attendees, through: :event_attendees, source: 'attendee'

  validates :event_name, presence: true
  validates :events_date, presence: true
  validates :location, presence: true

  scope :past_event, -> { where('events_date <?', Date.today) }
  scope :future_event, -> { where('events_date >?', Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attending_events, through: :event_attendees, source: 'event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    event = Event.find(params[:event_id])
    already_attended = event.event_attendees.find_by(attendee_id: current_user.id)

    if already_attended
      # redirect_to event_path(event)
    else
      @event_attendee = event.event_attendees.build(attendee_id: current_user.id)

      @event_attendee&.save ? flash[:notice] = 'Attendee added' : flash[:alert] = 'Failed to add attendee'

    end
    redirect_to event_path(event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @events = Event.all
    @past_events = @events.past_event
    @future_events = @events.future_event
  end

  def new
    @event = Event.new
  end

  def create
    user = User.find(current_user.id)
    @event = user.events.build(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :events_date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user = User.find(params[:id])
    @attending_events = user.attending_events
    @created_events = user.events
    @attended_past_events = @attending_events.past_event
    @upcoming_events = @attending_events.future_event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Home Page</h1><br>


<h3>The Up-coming Events</h3>
<% if @events.future_event.length < 1%>
<p>No Up-coming Events </p>
<% else%>
<ul>
<% @events.future_event.each do |event| %>
    <li>
    <%= link_to event.event_name, event_path(event.id) %><br>
    </li>
<%end%>
</ul>
<%end%>

<h3>The Past Events</h3>
<% if @events.past_event.length < 1%>
<p>No Past Events </p>
<% else%>
<ul>
<% @events.past_event.each do |event| %>
    <li>
    <%= link_to event.event_name, event_path(event.id)%><br>
    </li>
<%end%>
</ul>
<%end%>

app/views/events/new.html.erb
<h1>Event # new</h1>

<%= form_with model: @event do |form| %>
  <%= form.label :event_name, "Title of Event:"%> 
  <%= form.text_field :event_name%><br><br>

  <%= form.label :events_date, "Date of event:"%> 
  <%= form.text_field :events_date %><br><br>

  <%= form.label :location, "Location of event:"%> 
  <%= form.text_field :location %><br><br>

  <%= form.submit "Create Event" %>
 
<% end %>

app/views/events/show.html.erb
<h1>Events show page </h1>


<h2>Event Details</h2>

<p>Name: <%=  @event.event_name%><br></p>
<p>Date: <%= @event.events_date%><br></p>
<p>Location: <%= @event.location%><br> <br></p>

 <% if current_user.id==@event.creator.id%>
 <%= link_to "Delete Event", event_path(@event.id), :method => :delete %><br><br>
  <% end%>

 <% if @event.events_date > Date.today %>
 <%= link_to "Attend Event", event_event_attendees_path(@event), method: :post %><br><br>
 <% end%>
 
<h3>Attendees</h3>
<ul>
<% @event.attendees.each do |attendee| %>
    <li>
    <%=attendee.email%><br>
    </li>
<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "HOME", events_path %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
      <ul class="navbar-nav ms-auto">
  
       
        <li class="nav-item  ">
        <% if user_signed_in?%>
        <%= link_to "MY EVENTS", user_path(current_user.id) %>
        <%= link_to "CREATE EVENT", new_event_path %>
          <%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete, class:"btn btn-primary" %>
          <% else %> 
          <%= link_to "SIGN IN", user_session_path, class:"btn btn-primary" %>
        <% end %> 
        </li>
        
      </ul>
    </div>
  </div>
</nav>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>My Events</h1>


<h3>My Created Events</h3>
<% if @created_events.length < 1%>
<p>No Created Events </p>
<% else%>
<ul>
<% @created_events.each do |event| %>
    <li>
   <%= link_to event.event_name, event_path(event.id) %><br>
    </li>
<%end%>
</ul>
<%end%>

<h3>My Up-coming Attending Events</h3>
<% if @attending_events.future_event.length < 1%>
<p>No Up-coming Events </p>
<% else%>
<ul>
<% @attending_events.future_event.each do |event| %>
    <li>
    <%= link_to event.event_name, event_path(event.id) %><br>
    </li>
<%end%>
</ul>
<%end%>

<h3>My Past Attended Events</h3>
<% if @attending_events.past_event.length < 1%>
<p>No Past Events </p>
<% else%>
<ul>
<% @attending_events.past_event.each do |event| %>
    <li>
    <%= link_to event.event_name, event_path(event.id) %><br>
    </li>
<%end%>
</ul>
<%end %>